---
laser_scan_matcher:
  ros__parameters:
    # Main frames
    map_frame: "map"
    base_frame: "base_link"

    # Input laser scan
    laser_frame: "lidar_link"
    laser_scan_topic: "scan"

    # Output odom
    odom_frame: "odom"
    odom_topic: "laser_odom"  # If publish odometry from laser_scan.

    # Calculation options
    do_compute_covariance: 0  # 1: Compute covariance, 0: Use fixed covariance
    max_iterations: 10

    # Publishing outputs options
    publish_pose: true
    publish_pose_stamped: true
    publish_pose_with_covariance: true
    publish_pose_with_covariance_stamped: true

    used_odom_topic: ""  # "odom"
    vel_topic: "/cmd_vel"
